/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * OpenAPI spec version: 7.13.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Camunda.Client.Client;
using Camunda.Client.Api;
using Camunda.Client.Model;

namespace Camunda.Client.Test
{
    /// <summary>
    ///  Class for testing ProcessInstanceApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ProcessInstanceApiTests
    {
        private ProcessInstanceApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ProcessInstanceApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProcessInstanceApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ProcessInstanceApi
            //Assert.IsInstanceOfType(typeof(ProcessInstanceApi), instance, "instance is a ProcessInstanceApi");
        }

        /// <summary>
        /// Test DeleteAsyncHistoricQueryBased
        /// </summary>
        [Test]
        public void DeleteAsyncHistoricQueryBasedTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DeleteProcessInstancesDto body = null;
            //var response = instance.DeleteAsyncHistoricQueryBased(body);
            //Assert.IsInstanceOf<BatchDto> (response, "response is BatchDto");
        }
        /// <summary>
        /// Test DeleteProcessInstance
        /// </summary>
        [Test]
        public void DeleteProcessInstanceTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //bool? skipCustomListeners = null;
            //bool? skipIoMappings = null;
            //bool? skipSubprocesses = null;
            //bool? failIfNotExists = null;
            //instance.DeleteProcessInstance(id, skipCustomListeners, skipIoMappings, skipSubprocesses, failIfNotExists);
            
        }
        /// <summary>
        /// Test DeleteProcessInstanceVariable
        /// </summary>
        [Test]
        public void DeleteProcessInstanceVariableTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //string varName = null;
            //instance.DeleteProcessInstanceVariable(id, varName);
            
        }
        /// <summary>
        /// Test DeleteProcessInstancesAsyncOperation
        /// </summary>
        [Test]
        public void DeleteProcessInstancesAsyncOperationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DeleteProcessInstancesDto body = null;
            //var response = instance.DeleteProcessInstancesAsyncOperation(body);
            //Assert.IsInstanceOf<BatchDto> (response, "response is BatchDto");
        }
        /// <summary>
        /// Test GetActivityInstanceTree
        /// </summary>
        [Test]
        public void GetActivityInstanceTreeTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.GetActivityInstanceTree(id);
            //Assert.IsInstanceOf<ActivityInstanceDto> (response, "response is ActivityInstanceDto");
        }
        /// <summary>
        /// Test GetProcessInstanceVariable
        /// </summary>
        [Test]
        public void GetProcessInstanceVariableTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //string varName = null;
            //bool? deserializeValue = null;
            //var response = instance.GetProcessInstanceVariable(id, varName, deserializeValue);
            //Assert.IsInstanceOf<VariableValueDto> (response, "response is VariableValueDto");
        }
        /// <summary>
        /// Test GetProcessInstanceVariableBinary
        /// </summary>
        [Test]
        public void GetProcessInstanceVariableBinaryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //string varName = null;
            //var response = instance.GetProcessInstanceVariableBinary(id, varName);
            //Assert.IsInstanceOf<byte[]> (response, "response is byte[]");
        }
        /// <summary>
        /// Test GetProcessInstanceVariables
        /// </summary>
        [Test]
        public void GetProcessInstanceVariablesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //bool? deserializeValue = null;
            //var response = instance.GetProcessInstanceVariables(id, deserializeValue);
            //Assert.IsInstanceOf<Dictionary<string, VariableValueDto>> (response, "response is Dictionary<string, VariableValueDto>");
        }
        /// <summary>
        /// Test GetProcessInstances
        /// </summary>
        [Test]
        public void GetProcessInstancesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string sortBy = null;
            //string sortOrder = null;
            //int? firstResult = null;
            //int? maxResults = null;
            //string processInstanceIds = null;
            //string businessKey = null;
            //string businessKeyLike = null;
            //string caseInstanceId = null;
            //string processDefinitionId = null;
            //string processDefinitionKey = null;
            //string processDefinitionKeyIn = null;
            //string processDefinitionKeyNotIn = null;
            //string deploymentId = null;
            //string superProcessInstance = null;
            //string subProcessInstance = null;
            //string superCaseInstance = null;
            //string subCaseInstance = null;
            //bool? active = null;
            //bool? suspended = null;
            //bool? withIncident = null;
            //string incidentId = null;
            //string incidentType = null;
            //string incidentMessage = null;
            //string incidentMessageLike = null;
            //string tenantIdIn = null;
            //bool? withoutTenantId = null;
            //bool? processDefinitionWithoutTenantId = null;
            //string activityIdIn = null;
            //bool? rootProcessInstances = null;
            //bool? leafProcessInstances = null;
            //string variables = null;
            //bool? variableNamesIgnoreCase = null;
            //bool? variableValuesIgnoreCase = null;
            //var response = instance.GetProcessInstances(sortBy, sortOrder, firstResult, maxResults, processInstanceIds, businessKey, businessKeyLike, caseInstanceId, processDefinitionId, processDefinitionKey, processDefinitionKeyIn, processDefinitionKeyNotIn, deploymentId, superProcessInstance, subProcessInstance, superCaseInstance, subCaseInstance, active, suspended, withIncident, incidentId, incidentType, incidentMessage, incidentMessageLike, tenantIdIn, withoutTenantId, processDefinitionWithoutTenantId, activityIdIn, rootProcessInstances, leafProcessInstances, variables, variableNamesIgnoreCase, variableValuesIgnoreCase);
            //Assert.IsInstanceOf<List<ProcessInstanceDto>> (response, "response is List<ProcessInstanceDto>");
        }
        /// <summary>
        /// Test GetProcessInstancesCount
        /// </summary>
        [Test]
        public void GetProcessInstancesCountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string processInstanceIds = null;
            //string businessKey = null;
            //string businessKeyLike = null;
            //string caseInstanceId = null;
            //string processDefinitionId = null;
            //string processDefinitionKey = null;
            //string processDefinitionKeyIn = null;
            //string processDefinitionKeyNotIn = null;
            //string deploymentId = null;
            //string superProcessInstance = null;
            //string subProcessInstance = null;
            //string superCaseInstance = null;
            //string subCaseInstance = null;
            //bool? active = null;
            //bool? suspended = null;
            //bool? withIncident = null;
            //string incidentId = null;
            //string incidentType = null;
            //string incidentMessage = null;
            //string incidentMessageLike = null;
            //string tenantIdIn = null;
            //bool? withoutTenantId = null;
            //bool? processDefinitionWithoutTenantId = null;
            //string activityIdIn = null;
            //bool? rootProcessInstances = null;
            //bool? leafProcessInstances = null;
            //string variables = null;
            //bool? variableNamesIgnoreCase = null;
            //bool? variableValuesIgnoreCase = null;
            //var response = instance.GetProcessInstancesCount(processInstanceIds, businessKey, businessKeyLike, caseInstanceId, processDefinitionId, processDefinitionKey, processDefinitionKeyIn, processDefinitionKeyNotIn, deploymentId, superProcessInstance, subProcessInstance, superCaseInstance, subCaseInstance, active, suspended, withIncident, incidentId, incidentType, incidentMessage, incidentMessageLike, tenantIdIn, withoutTenantId, processDefinitionWithoutTenantId, activityIdIn, rootProcessInstances, leafProcessInstances, variables, variableNamesIgnoreCase, variableValuesIgnoreCase);
            //Assert.IsInstanceOf<CountResultDto> (response, "response is CountResultDto");
        }
        /// <summary>
        /// Test ModifyProcessInstance
        /// </summary>
        [Test]
        public void ModifyProcessInstanceTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //ProcessInstanceModificationDto body = null;
            //instance.ModifyProcessInstance(id, body);
            
        }
        /// <summary>
        /// Test ModifyProcessInstanceAsyncOperation
        /// </summary>
        [Test]
        public void ModifyProcessInstanceAsyncOperationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //ProcessInstanceModificationDto body = null;
            //var response = instance.ModifyProcessInstanceAsyncOperation(id, body);
            //Assert.IsInstanceOf<BatchDto> (response, "response is BatchDto");
        }
        /// <summary>
        /// Test ModifyProcessInstanceVariables
        /// </summary>
        [Test]
        public void ModifyProcessInstanceVariablesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //PatchVariablesDto body = null;
            //instance.ModifyProcessInstanceVariables(id, body);
            
        }
        /// <summary>
        /// Test QueryProcessInstances
        /// </summary>
        [Test]
        public void QueryProcessInstancesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ProcessInstanceQueryDto body = null;
            //int? firstResult = null;
            //int? maxResults = null;
            //var response = instance.QueryProcessInstances(body, firstResult, maxResults);
            //Assert.IsInstanceOf<List<ProcessInstanceDto>> (response, "response is List<ProcessInstanceDto>");
        }
        /// <summary>
        /// Test QueryProcessInstancesCount
        /// </summary>
        [Test]
        public void QueryProcessInstancesCountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ProcessInstanceQueryDto body = null;
            //var response = instance.QueryProcessInstancesCount(body);
            //Assert.IsInstanceOf<CountResultDto> (response, "response is CountResultDto");
        }
        /// <summary>
        /// Test SetProcessInstanceVariable
        /// </summary>
        [Test]
        public void SetProcessInstanceVariableTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //string varName = null;
            //VariableValueDto body = null;
            //instance.SetProcessInstanceVariable(id, varName, body);
            
        }
        /// <summary>
        /// Test SetProcessInstanceVariableBinary
        /// </summary>
        [Test]
        public void SetProcessInstanceVariableBinaryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //string varName = null;
            //byte[] data = null;
            //string valueType = null;
            //instance.SetProcessInstanceVariableBinary(id, varName, data, valueType);
            
        }
        /// <summary>
        /// Test SetRetriesByProcess
        /// </summary>
        [Test]
        public void SetRetriesByProcessTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SetJobRetriesByProcessDto body = null;
            //var response = instance.SetRetriesByProcess(body);
            //Assert.IsInstanceOf<BatchDto> (response, "response is BatchDto");
        }
        /// <summary>
        /// Test SetRetriesByProcessHistoricQueryBased
        /// </summary>
        [Test]
        public void SetRetriesByProcessHistoricQueryBasedTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SetJobRetriesByProcessDto body = null;
            //var response = instance.SetRetriesByProcessHistoricQueryBased(body);
            //Assert.IsInstanceOf<BatchDto> (response, "response is BatchDto");
        }
        /// <summary>
        /// Test UpdateSuspensionState
        /// </summary>
        [Test]
        public void UpdateSuspensionStateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ProcessInstanceSuspensionStateDto body = null;
            //instance.UpdateSuspensionState(body);
            
        }
        /// <summary>
        /// Test UpdateSuspensionStateAsyncOperation
        /// </summary>
        [Test]
        public void UpdateSuspensionStateAsyncOperationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ProcessInstanceSuspensionStateAsyncDto body = null;
            //var response = instance.UpdateSuspensionStateAsyncOperation(body);
            //Assert.IsInstanceOf<BatchDto> (response, "response is BatchDto");
        }
        /// <summary>
        /// Test UpdateSuspensionStateById
        /// </summary>
        [Test]
        public void UpdateSuspensionStateByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //SuspensionStateDto body = null;
            //instance.UpdateSuspensionStateById(id, body);
            
        }
    }

}
