/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * OpenAPI spec version: 7.13.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Camunda.Client.Client;
using Camunda.Client.Api;
using Camunda.Client.Model;

namespace Camunda.Client.Test
{
    /// <summary>
    ///  Class for testing SchemaLogApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class SchemaLogApiTests
    {
        private SchemaLogApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new SchemaLogApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SchemaLogApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' SchemaLogApi
            //Assert.IsInstanceOfType(typeof(SchemaLogApi), instance, "instance is a SchemaLogApi");
        }

        /// <summary>
        /// Test GetSchemaLog
        /// </summary>
        [Test]
        public void GetSchemaLogTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string version = null;
            //int? firstResult = null;
            //int? maxResults = null;
            //var response = instance.GetSchemaLog(version, firstResult, maxResults);
            //Assert.IsInstanceOf<List<SchemaLogEntryDto>> (response, "response is List<SchemaLogEntryDto>");
        }
        /// <summary>
        /// Test QuerySchemaLog
        /// </summary>
        [Test]
        public void QuerySchemaLogTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SchemaLogQueryDto body = null;
            //int? firstResult = null;
            //int? maxResults = null;
            //var response = instance.QuerySchemaLog(body, firstResult, maxResults);
            //Assert.IsInstanceOf<List<SchemaLogEntryDto>> (response, "response is List<SchemaLogEntryDto>");
        }
    }

}
