/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * OpenAPI spec version: 7.13.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Camunda.Client.Client;
using Camunda.Client.Api;
using Camunda.Client.Model;

namespace Camunda.Client.Test
{
    /// <summary>
    ///  Class for testing TaskVariableApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class TaskVariableApiTests
    {
        private TaskVariableApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new TaskVariableApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TaskVariableApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' TaskVariableApi
            //Assert.IsInstanceOfType(typeof(TaskVariableApi), instance, "instance is a TaskVariableApi");
        }

        /// <summary>
        /// Test DeleteTaskVariable
        /// </summary>
        [Test]
        public void DeleteTaskVariableTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //string varName = null;
            //instance.DeleteTaskVariable(id, varName);
            
        }
        /// <summary>
        /// Test GetTaskVariable
        /// </summary>
        [Test]
        public void GetTaskVariableTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //string varName = null;
            //bool? deserializeValue = null;
            //var response = instance.GetTaskVariable(id, varName, deserializeValue);
            //Assert.IsInstanceOf<VariableValueDto> (response, "response is VariableValueDto");
        }
        /// <summary>
        /// Test GetTaskVariableBinary
        /// </summary>
        [Test]
        public void GetTaskVariableBinaryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //string varName = null;
            //var response = instance.GetTaskVariableBinary(id, varName);
            //Assert.IsInstanceOf<byte[]> (response, "response is byte[]");
        }
        /// <summary>
        /// Test GetTaskVariables
        /// </summary>
        [Test]
        public void GetTaskVariablesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //bool? deserializeValue = null;
            //var response = instance.GetTaskVariables(id, deserializeValue);
            //Assert.IsInstanceOf<Dictionary<string, VariableValueDto>> (response, "response is Dictionary<string, VariableValueDto>");
        }
        /// <summary>
        /// Test ModifyTaskVariables
        /// </summary>
        [Test]
        public void ModifyTaskVariablesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //PatchVariablesDto body = null;
            //instance.ModifyTaskVariables(id, body);
            
        }
        /// <summary>
        /// Test PutTaskVariable
        /// </summary>
        [Test]
        public void PutTaskVariableTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //string varName = null;
            //VariableValueDto body = null;
            //instance.PutTaskVariable(id, varName, body);
            
        }
        /// <summary>
        /// Test SetBinaryTaskVariable
        /// </summary>
        [Test]
        public void SetBinaryTaskVariableTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //string varName = null;
            //byte[] data = null;
            //string valueType = null;
            //instance.SetBinaryTaskVariable(id, varName, data, valueType);
            
        }
    }

}
