/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * OpenAPI spec version: 7.13.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Camunda.Client.Client;
using Camunda.Client.Api;
using Camunda.Client.Model;

namespace Camunda.Client.Test
{
    /// <summary>
    ///  Class for testing TaskIdentityLinkApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class TaskIdentityLinkApiTests
    {
        private TaskIdentityLinkApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new TaskIdentityLinkApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TaskIdentityLinkApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' TaskIdentityLinkApi
            //Assert.IsInstanceOfType(typeof(TaskIdentityLinkApi), instance, "instance is a TaskIdentityLinkApi");
        }

        /// <summary>
        /// Test AddIdentityLink
        /// </summary>
        [Test]
        public void AddIdentityLinkTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //IdentityLinkDto body = null;
            //instance.AddIdentityLink(id, body);
            
        }
        /// <summary>
        /// Test DeleteIdentityLink
        /// </summary>
        [Test]
        public void DeleteIdentityLinkTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //IdentityLinkDto body = null;
            //instance.DeleteIdentityLink(id, body);
            
        }
        /// <summary>
        /// Test GetIdentityLinks
        /// </summary>
        [Test]
        public void GetIdentityLinksTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //string type = null;
            //var response = instance.GetIdentityLinks(id, type);
            //Assert.IsInstanceOf<List<IdentityLinkDto>> (response, "response is List<IdentityLinkDto>");
        }
    }

}
