/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * OpenAPI spec version: 7.13.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Camunda.Client.Api;
using Camunda.Client.Model;
using Camunda.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Camunda.Client.Test
{
    /// <summary>
    ///  Class for testing ActivityInstanceIncidentDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ActivityInstanceIncidentDtoTests
    {
        // TODO uncomment below to declare an instance variable for ActivityInstanceIncidentDto
        //private ActivityInstanceIncidentDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ActivityInstanceIncidentDto
            //instance = new ActivityInstanceIncidentDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ActivityInstanceIncidentDto
        /// </summary>
        [Test]
        public void ActivityInstanceIncidentDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ActivityInstanceIncidentDto
            //Assert.IsInstanceOfType<ActivityInstanceIncidentDto> (instance, "variable 'instance' is a ActivityInstanceIncidentDto");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ParentActivityInstanceId'
        /// </summary>
        [Test]
        public void ParentActivityInstanceIdTest()
        {
            // TODO unit test for the property 'ParentActivityInstanceId'
        }

    }

}
