/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * OpenAPI spec version: 7.13.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Camunda.Client.Api;
using Camunda.Client.Model;
using Camunda.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Camunda.Client.Test
{
    /// <summary>
    ///  Class for testing BatchDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BatchDtoTests
    {
        // TODO uncomment below to declare an instance variable for BatchDto
        //private BatchDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BatchDto
            //instance = new BatchDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BatchDto
        /// </summary>
        [Test]
        public void BatchDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BatchDto
            //Assert.IsInstanceOfType<BatchDto> (instance, "variable 'instance' is a BatchDto");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'TotalJobs'
        /// </summary>
        [Test]
        public void TotalJobsTest()
        {
            // TODO unit test for the property 'TotalJobs'
        }
        /// <summary>
        /// Test the property 'JobsCreated'
        /// </summary>
        [Test]
        public void JobsCreatedTest()
        {
            // TODO unit test for the property 'JobsCreated'
        }
        /// <summary>
        /// Test the property 'BatchJobsPerSeed'
        /// </summary>
        [Test]
        public void BatchJobsPerSeedTest()
        {
            // TODO unit test for the property 'BatchJobsPerSeed'
        }
        /// <summary>
        /// Test the property 'InvocationsPerBatchJob'
        /// </summary>
        [Test]
        public void InvocationsPerBatchJobTest()
        {
            // TODO unit test for the property 'InvocationsPerBatchJob'
        }
        /// <summary>
        /// Test the property 'SeedJobDefinitionId'
        /// </summary>
        [Test]
        public void SeedJobDefinitionIdTest()
        {
            // TODO unit test for the property 'SeedJobDefinitionId'
        }
        /// <summary>
        /// Test the property 'MonitorJobDefinitionId'
        /// </summary>
        [Test]
        public void MonitorJobDefinitionIdTest()
        {
            // TODO unit test for the property 'MonitorJobDefinitionId'
        }
        /// <summary>
        /// Test the property 'BatchJobDefinitionId'
        /// </summary>
        [Test]
        public void BatchJobDefinitionIdTest()
        {
            // TODO unit test for the property 'BatchJobDefinitionId'
        }
        /// <summary>
        /// Test the property 'Suspended'
        /// </summary>
        [Test]
        public void SuspendedTest()
        {
            // TODO unit test for the property 'Suspended'
        }
        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Test]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }
        /// <summary>
        /// Test the property 'CreateUserId'
        /// </summary>
        [Test]
        public void CreateUserIdTest()
        {
            // TODO unit test for the property 'CreateUserId'
        }

    }

}
