/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * OpenAPI spec version: 7.13.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Camunda.Client.Api;
using Camunda.Client.Model;
using Camunda.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Camunda.Client.Test
{
    /// <summary>
    ///  Class for testing CorrelationMessageDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CorrelationMessageDtoTests
    {
        // TODO uncomment below to declare an instance variable for CorrelationMessageDto
        //private CorrelationMessageDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CorrelationMessageDto
            //instance = new CorrelationMessageDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CorrelationMessageDto
        /// </summary>
        [Test]
        public void CorrelationMessageDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CorrelationMessageDto
            //Assert.IsInstanceOfType<CorrelationMessageDto> (instance, "variable 'instance' is a CorrelationMessageDto");
        }


        /// <summary>
        /// Test the property 'MessageName'
        /// </summary>
        [Test]
        public void MessageNameTest()
        {
            // TODO unit test for the property 'MessageName'
        }
        /// <summary>
        /// Test the property 'BusinessKey'
        /// </summary>
        [Test]
        public void BusinessKeyTest()
        {
            // TODO unit test for the property 'BusinessKey'
        }
        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Test]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }
        /// <summary>
        /// Test the property 'WithoutTenantId'
        /// </summary>
        [Test]
        public void WithoutTenantIdTest()
        {
            // TODO unit test for the property 'WithoutTenantId'
        }
        /// <summary>
        /// Test the property 'ProcessInstanceId'
        /// </summary>
        [Test]
        public void ProcessInstanceIdTest()
        {
            // TODO unit test for the property 'ProcessInstanceId'
        }
        /// <summary>
        /// Test the property 'CorrelationKeys'
        /// </summary>
        [Test]
        public void CorrelationKeysTest()
        {
            // TODO unit test for the property 'CorrelationKeys'
        }
        /// <summary>
        /// Test the property 'LocalCorrelationKeys'
        /// </summary>
        [Test]
        public void LocalCorrelationKeysTest()
        {
            // TODO unit test for the property 'LocalCorrelationKeys'
        }
        /// <summary>
        /// Test the property 'ProcessVariables'
        /// </summary>
        [Test]
        public void ProcessVariablesTest()
        {
            // TODO unit test for the property 'ProcessVariables'
        }
        /// <summary>
        /// Test the property 'ProcessVariablesLocal'
        /// </summary>
        [Test]
        public void ProcessVariablesLocalTest()
        {
            // TODO unit test for the property 'ProcessVariablesLocal'
        }
        /// <summary>
        /// Test the property 'All'
        /// </summary>
        [Test]
        public void AllTest()
        {
            // TODO unit test for the property 'All'
        }
        /// <summary>
        /// Test the property 'ResultEnabled'
        /// </summary>
        [Test]
        public void ResultEnabledTest()
        {
            // TODO unit test for the property 'ResultEnabled'
        }
        /// <summary>
        /// Test the property 'VariablesInResultEnabled'
        /// </summary>
        [Test]
        public void VariablesInResultEnabledTest()
        {
            // TODO unit test for the property 'VariablesInResultEnabled'
        }

    }

}
