/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * OpenAPI spec version: 7.13.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Camunda.Client.Api;
using Camunda.Client.Model;
using Camunda.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Camunda.Client.Test
{
    /// <summary>
    ///  Class for testing DecisionDefinitionDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DecisionDefinitionDtoTests
    {
        // TODO uncomment below to declare an instance variable for DecisionDefinitionDto
        //private DecisionDefinitionDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DecisionDefinitionDto
            //instance = new DecisionDefinitionDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DecisionDefinitionDto
        /// </summary>
        [Test]
        public void DecisionDefinitionDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DecisionDefinitionDto
            //Assert.IsInstanceOfType<DecisionDefinitionDto> (instance, "variable 'instance' is a DecisionDefinitionDto");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Test]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Test]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }
        /// <summary>
        /// Test the property 'Resource'
        /// </summary>
        [Test]
        public void ResourceTest()
        {
            // TODO unit test for the property 'Resource'
        }
        /// <summary>
        /// Test the property 'DeploymentId'
        /// </summary>
        [Test]
        public void DeploymentIdTest()
        {
            // TODO unit test for the property 'DeploymentId'
        }
        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Test]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }
        /// <summary>
        /// Test the property 'DecisionRequirementsDefinitionId'
        /// </summary>
        [Test]
        public void DecisionRequirementsDefinitionIdTest()
        {
            // TODO unit test for the property 'DecisionRequirementsDefinitionId'
        }
        /// <summary>
        /// Test the property 'DecisionRequirementsDefinitionKey'
        /// </summary>
        [Test]
        public void DecisionRequirementsDefinitionKeyTest()
        {
            // TODO unit test for the property 'DecisionRequirementsDefinitionKey'
        }
        /// <summary>
        /// Test the property 'HistoryTimeToLive'
        /// </summary>
        [Test]
        public void HistoryTimeToLiveTest()
        {
            // TODO unit test for the property 'HistoryTimeToLive'
        }
        /// <summary>
        /// Test the property 'VersionTag'
        /// </summary>
        [Test]
        public void VersionTagTest()
        {
            // TODO unit test for the property 'VersionTag'
        }

    }

}
