/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * OpenAPI spec version: 7.13.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Camunda.Client.Api;
using Camunda.Client.Model;
using Camunda.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Camunda.Client.Test
{
    /// <summary>
    ///  Class for testing DeleteProcessInstancesDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DeleteProcessInstancesDtoTests
    {
        // TODO uncomment below to declare an instance variable for DeleteProcessInstancesDto
        //private DeleteProcessInstancesDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DeleteProcessInstancesDto
            //instance = new DeleteProcessInstancesDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DeleteProcessInstancesDto
        /// </summary>
        [Test]
        public void DeleteProcessInstancesDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DeleteProcessInstancesDto
            //Assert.IsInstanceOfType<DeleteProcessInstancesDto> (instance, "variable 'instance' is a DeleteProcessInstancesDto");
        }


        /// <summary>
        /// Test the property 'ProcessInstanceIds'
        /// </summary>
        [Test]
        public void ProcessInstanceIdsTest()
        {
            // TODO unit test for the property 'ProcessInstanceIds'
        }
        /// <summary>
        /// Test the property 'DeleteReason'
        /// </summary>
        [Test]
        public void DeleteReasonTest()
        {
            // TODO unit test for the property 'DeleteReason'
        }
        /// <summary>
        /// Test the property 'SkipCustomListeners'
        /// </summary>
        [Test]
        public void SkipCustomListenersTest()
        {
            // TODO unit test for the property 'SkipCustomListeners'
        }
        /// <summary>
        /// Test the property 'SkipSubprocesses'
        /// </summary>
        [Test]
        public void SkipSubprocessesTest()
        {
            // TODO unit test for the property 'SkipSubprocesses'
        }
        /// <summary>
        /// Test the property 'ProcessInstanceQuery'
        /// </summary>
        [Test]
        public void ProcessInstanceQueryTest()
        {
            // TODO unit test for the property 'ProcessInstanceQuery'
        }
        /// <summary>
        /// Test the property 'HistoricProcessInstanceQuery'
        /// </summary>
        [Test]
        public void HistoricProcessInstanceQueryTest()
        {
            // TODO unit test for the property 'HistoricProcessInstanceQuery'
        }

    }

}
