/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * OpenAPI spec version: 7.13.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Camunda.Client.Api;
using Camunda.Client.Model;
using Camunda.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Camunda.Client.Test
{
    /// <summary>
    ///  Class for testing DeploymentDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DeploymentDtoTests
    {
        // TODO uncomment below to declare an instance variable for DeploymentDto
        //private DeploymentDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DeploymentDto
            //instance = new DeploymentDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DeploymentDto
        /// </summary>
        [Test]
        public void DeploymentDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DeploymentDto
            //Assert.IsInstanceOfType<DeploymentDto> (instance, "variable 'instance' is a DeploymentDto");
        }


        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Test]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }

    }

}
