/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * OpenAPI spec version: 7.13.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Camunda.Client.Api;
using Camunda.Client.Model;
using Camunda.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Camunda.Client.Test
{
    /// <summary>
    ///  Class for testing DeploymentResourceDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DeploymentResourceDtoTests
    {
        // TODO uncomment below to declare an instance variable for DeploymentResourceDto
        //private DeploymentResourceDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DeploymentResourceDto
            //instance = new DeploymentResourceDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DeploymentResourceDto
        /// </summary>
        [Test]
        public void DeploymentResourceDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DeploymentResourceDto
            //Assert.IsInstanceOfType<DeploymentResourceDto> (instance, "variable 'instance' is a DeploymentResourceDto");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'DeploymentId'
        /// </summary>
        [Test]
        public void DeploymentIdTest()
        {
            // TODO unit test for the property 'DeploymentId'
        }

    }

}
