/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * OpenAPI spec version: 7.13.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Camunda.Client.Api;
using Camunda.Client.Model;
using Camunda.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Camunda.Client.Test
{
    /// <summary>
    ///  Class for testing ExternalTaskFailureDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ExternalTaskFailureDtoTests
    {
        // TODO uncomment below to declare an instance variable for ExternalTaskFailureDto
        //private ExternalTaskFailureDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ExternalTaskFailureDto
            //instance = new ExternalTaskFailureDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ExternalTaskFailureDto
        /// </summary>
        [Test]
        public void ExternalTaskFailureDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ExternalTaskFailureDto
            //Assert.IsInstanceOfType<ExternalTaskFailureDto> (instance, "variable 'instance' is a ExternalTaskFailureDto");
        }


        /// <summary>
        /// Test the property 'WorkerId'
        /// </summary>
        [Test]
        public void WorkerIdTest()
        {
            // TODO unit test for the property 'WorkerId'
        }
        /// <summary>
        /// Test the property 'ErrorMessage'
        /// </summary>
        [Test]
        public void ErrorMessageTest()
        {
            // TODO unit test for the property 'ErrorMessage'
        }
        /// <summary>
        /// Test the property 'ErrorDetails'
        /// </summary>
        [Test]
        public void ErrorDetailsTest()
        {
            // TODO unit test for the property 'ErrorDetails'
        }
        /// <summary>
        /// Test the property 'Retries'
        /// </summary>
        [Test]
        public void RetriesTest()
        {
            // TODO unit test for the property 'Retries'
        }
        /// <summary>
        /// Test the property 'RetryTimeout'
        /// </summary>
        [Test]
        public void RetryTimeoutTest()
        {
            // TODO unit test for the property 'RetryTimeout'
        }

    }

}
