/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * OpenAPI spec version: 7.13.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Camunda.Client.Api;
using Camunda.Client.Model;
using Camunda.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Camunda.Client.Test
{
    /// <summary>
    ///  Class for testing ExtendLockOnExternalTaskDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ExtendLockOnExternalTaskDtoTests
    {
        // TODO uncomment below to declare an instance variable for ExtendLockOnExternalTaskDto
        //private ExtendLockOnExternalTaskDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ExtendLockOnExternalTaskDto
            //instance = new ExtendLockOnExternalTaskDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ExtendLockOnExternalTaskDto
        /// </summary>
        [Test]
        public void ExtendLockOnExternalTaskDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ExtendLockOnExternalTaskDto
            //Assert.IsInstanceOfType<ExtendLockOnExternalTaskDto> (instance, "variable 'instance' is a ExtendLockOnExternalTaskDto");
        }


        /// <summary>
        /// Test the property 'WorkerId'
        /// </summary>
        [Test]
        public void WorkerIdTest()
        {
            // TODO unit test for the property 'WorkerId'
        }
        /// <summary>
        /// Test the property 'NewDuration'
        /// </summary>
        [Test]
        public void NewDurationTest()
        {
            // TODO unit test for the property 'NewDuration'
        }

    }

}
