/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * OpenAPI spec version: 7.13.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Camunda.Client.Api;
using Camunda.Client.Model;
using Camunda.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Camunda.Client.Test
{
    /// <summary>
    ///  Class for testing FetchExternalTasksDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FetchExternalTasksDtoTests
    {
        // TODO uncomment below to declare an instance variable for FetchExternalTasksDto
        //private FetchExternalTasksDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FetchExternalTasksDto
            //instance = new FetchExternalTasksDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FetchExternalTasksDto
        /// </summary>
        [Test]
        public void FetchExternalTasksDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FetchExternalTasksDto
            //Assert.IsInstanceOfType<FetchExternalTasksDto> (instance, "variable 'instance' is a FetchExternalTasksDto");
        }


        /// <summary>
        /// Test the property 'WorkerId'
        /// </summary>
        [Test]
        public void WorkerIdTest()
        {
            // TODO unit test for the property 'WorkerId'
        }
        /// <summary>
        /// Test the property 'MaxTasks'
        /// </summary>
        [Test]
        public void MaxTasksTest()
        {
            // TODO unit test for the property 'MaxTasks'
        }
        /// <summary>
        /// Test the property 'UsePriority'
        /// </summary>
        [Test]
        public void UsePriorityTest()
        {
            // TODO unit test for the property 'UsePriority'
        }
        /// <summary>
        /// Test the property 'AsyncResponseTimeout'
        /// </summary>
        [Test]
        public void AsyncResponseTimeoutTest()
        {
            // TODO unit test for the property 'AsyncResponseTimeout'
        }
        /// <summary>
        /// Test the property 'Topics'
        /// </summary>
        [Test]
        public void TopicsTest()
        {
            // TODO unit test for the property 'Topics'
        }

    }

}
