/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * OpenAPI spec version: 7.13.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Camunda.Client.Api;
using Camunda.Client.Model;
using Camunda.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Camunda.Client.Test
{
    /// <summary>
    ///  Class for testing FetchExternalTaskTopicDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FetchExternalTaskTopicDtoTests
    {
        // TODO uncomment below to declare an instance variable for FetchExternalTaskTopicDto
        //private FetchExternalTaskTopicDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FetchExternalTaskTopicDto
            //instance = new FetchExternalTaskTopicDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FetchExternalTaskTopicDto
        /// </summary>
        [Test]
        public void FetchExternalTaskTopicDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FetchExternalTaskTopicDto
            //Assert.IsInstanceOfType<FetchExternalTaskTopicDto> (instance, "variable 'instance' is a FetchExternalTaskTopicDto");
        }


        /// <summary>
        /// Test the property 'TopicName'
        /// </summary>
        [Test]
        public void TopicNameTest()
        {
            // TODO unit test for the property 'TopicName'
        }
        /// <summary>
        /// Test the property 'LockDuration'
        /// </summary>
        [Test]
        public void LockDurationTest()
        {
            // TODO unit test for the property 'LockDuration'
        }
        /// <summary>
        /// Test the property 'Variables'
        /// </summary>
        [Test]
        public void VariablesTest()
        {
            // TODO unit test for the property 'Variables'
        }
        /// <summary>
        /// Test the property 'LocalVariables'
        /// </summary>
        [Test]
        public void LocalVariablesTest()
        {
            // TODO unit test for the property 'LocalVariables'
        }
        /// <summary>
        /// Test the property 'BusinessKey'
        /// </summary>
        [Test]
        public void BusinessKeyTest()
        {
            // TODO unit test for the property 'BusinessKey'
        }
        /// <summary>
        /// Test the property 'ProcessDefinitionId'
        /// </summary>
        [Test]
        public void ProcessDefinitionIdTest()
        {
            // TODO unit test for the property 'ProcessDefinitionId'
        }
        /// <summary>
        /// Test the property 'ProcessDefinitionIdIn'
        /// </summary>
        [Test]
        public void ProcessDefinitionIdInTest()
        {
            // TODO unit test for the property 'ProcessDefinitionIdIn'
        }
        /// <summary>
        /// Test the property 'ProcessDefinitionKey'
        /// </summary>
        [Test]
        public void ProcessDefinitionKeyTest()
        {
            // TODO unit test for the property 'ProcessDefinitionKey'
        }
        /// <summary>
        /// Test the property 'ProcessDefinitionKeyIn'
        /// </summary>
        [Test]
        public void ProcessDefinitionKeyInTest()
        {
            // TODO unit test for the property 'ProcessDefinitionKeyIn'
        }
        /// <summary>
        /// Test the property 'ProcessDefinitionVersionTag'
        /// </summary>
        [Test]
        public void ProcessDefinitionVersionTagTest()
        {
            // TODO unit test for the property 'ProcessDefinitionVersionTag'
        }
        /// <summary>
        /// Test the property 'WithoutTenantId'
        /// </summary>
        [Test]
        public void WithoutTenantIdTest()
        {
            // TODO unit test for the property 'WithoutTenantId'
        }
        /// <summary>
        /// Test the property 'TenantIdIn'
        /// </summary>
        [Test]
        public void TenantIdInTest()
        {
            // TODO unit test for the property 'TenantIdIn'
        }
        /// <summary>
        /// Test the property 'ProcessVariables'
        /// </summary>
        [Test]
        public void ProcessVariablesTest()
        {
            // TODO unit test for the property 'ProcessVariables'
        }
        /// <summary>
        /// Test the property 'DeserializeValues'
        /// </summary>
        [Test]
        public void DeserializeValuesTest()
        {
            // TODO unit test for the property 'DeserializeValues'
        }

    }

}
