/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * OpenAPI spec version: 7.13.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Camunda.Client.Api;
using Camunda.Client.Model;
using Camunda.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Camunda.Client.Test
{
    /// <summary>
    ///  Class for testing HistoricProcessInstanceQueryDtoSorting
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class HistoricProcessInstanceQueryDtoSortingTests
    {
        // TODO uncomment below to declare an instance variable for HistoricProcessInstanceQueryDtoSorting
        //private HistoricProcessInstanceQueryDtoSorting instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of HistoricProcessInstanceQueryDtoSorting
            //instance = new HistoricProcessInstanceQueryDtoSorting();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HistoricProcessInstanceQueryDtoSorting
        /// </summary>
        [Test]
        public void HistoricProcessInstanceQueryDtoSortingInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HistoricProcessInstanceQueryDtoSorting
            //Assert.IsInstanceOfType<HistoricProcessInstanceQueryDtoSorting> (instance, "variable 'instance' is a HistoricProcessInstanceQueryDtoSorting");
        }


        /// <summary>
        /// Test the property 'SortBy'
        /// </summary>
        [Test]
        public void SortByTest()
        {
            // TODO unit test for the property 'SortBy'
        }
        /// <summary>
        /// Test the property 'SortOrder'
        /// </summary>
        [Test]
        public void SortOrderTest()
        {
            // TODO unit test for the property 'SortOrder'
        }

    }

}
