/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * OpenAPI spec version: 7.13.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Camunda.Client.Api;
using Camunda.Client.Model;
using Camunda.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Camunda.Client.Test
{
    /// <summary>
    ///  Class for testing LockedExternalTaskDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LockedExternalTaskDtoTests
    {
        // TODO uncomment below to declare an instance variable for LockedExternalTaskDto
        //private LockedExternalTaskDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LockedExternalTaskDto
            //instance = new LockedExternalTaskDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LockedExternalTaskDto
        /// </summary>
        [Test]
        public void LockedExternalTaskDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LockedExternalTaskDto
            //Assert.IsInstanceOfType<LockedExternalTaskDto> (instance, "variable 'instance' is a LockedExternalTaskDto");
        }


        /// <summary>
        /// Test the property 'ActivityId'
        /// </summary>
        [Test]
        public void ActivityIdTest()
        {
            // TODO unit test for the property 'ActivityId'
        }
        /// <summary>
        /// Test the property 'ActivityInstanceId'
        /// </summary>
        [Test]
        public void ActivityInstanceIdTest()
        {
            // TODO unit test for the property 'ActivityInstanceId'
        }
        /// <summary>
        /// Test the property 'ErrorMessage'
        /// </summary>
        [Test]
        public void ErrorMessageTest()
        {
            // TODO unit test for the property 'ErrorMessage'
        }
        /// <summary>
        /// Test the property 'ErrorDetails'
        /// </summary>
        [Test]
        public void ErrorDetailsTest()
        {
            // TODO unit test for the property 'ErrorDetails'
        }
        /// <summary>
        /// Test the property 'ExecutionId'
        /// </summary>
        [Test]
        public void ExecutionIdTest()
        {
            // TODO unit test for the property 'ExecutionId'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'LockExpirationTime'
        /// </summary>
        [Test]
        public void LockExpirationTimeTest()
        {
            // TODO unit test for the property 'LockExpirationTime'
        }
        /// <summary>
        /// Test the property 'ProcessDefinitionId'
        /// </summary>
        [Test]
        public void ProcessDefinitionIdTest()
        {
            // TODO unit test for the property 'ProcessDefinitionId'
        }
        /// <summary>
        /// Test the property 'ProcessDefinitionKey'
        /// </summary>
        [Test]
        public void ProcessDefinitionKeyTest()
        {
            // TODO unit test for the property 'ProcessDefinitionKey'
        }
        /// <summary>
        /// Test the property 'ProcessDefinitionVersionTag'
        /// </summary>
        [Test]
        public void ProcessDefinitionVersionTagTest()
        {
            // TODO unit test for the property 'ProcessDefinitionVersionTag'
        }
        /// <summary>
        /// Test the property 'ProcessInstanceId'
        /// </summary>
        [Test]
        public void ProcessInstanceIdTest()
        {
            // TODO unit test for the property 'ProcessInstanceId'
        }
        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Test]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }
        /// <summary>
        /// Test the property 'Retries'
        /// </summary>
        [Test]
        public void RetriesTest()
        {
            // TODO unit test for the property 'Retries'
        }
        /// <summary>
        /// Test the property 'Suspended'
        /// </summary>
        [Test]
        public void SuspendedTest()
        {
            // TODO unit test for the property 'Suspended'
        }
        /// <summary>
        /// Test the property 'WorkerId'
        /// </summary>
        [Test]
        public void WorkerIdTest()
        {
            // TODO unit test for the property 'WorkerId'
        }
        /// <summary>
        /// Test the property 'Priority'
        /// </summary>
        [Test]
        public void PriorityTest()
        {
            // TODO unit test for the property 'Priority'
        }
        /// <summary>
        /// Test the property 'TopicName'
        /// </summary>
        [Test]
        public void TopicNameTest()
        {
            // TODO unit test for the property 'TopicName'
        }
        /// <summary>
        /// Test the property 'BusinessKey'
        /// </summary>
        [Test]
        public void BusinessKeyTest()
        {
            // TODO unit test for the property 'BusinessKey'
        }
        /// <summary>
        /// Test the property 'Variables'
        /// </summary>
        [Test]
        public void VariablesTest()
        {
            // TODO unit test for the property 'Variables'
        }

    }

}
