/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * OpenAPI spec version: 7.13.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Camunda.Client.Api;
using Camunda.Client.Model;
using Camunda.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Camunda.Client.Test
{
    /// <summary>
    ///  Class for testing MessageCorrelationResultWithVariableDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MessageCorrelationResultWithVariableDtoTests
    {
        // TODO uncomment below to declare an instance variable for MessageCorrelationResultWithVariableDto
        //private MessageCorrelationResultWithVariableDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MessageCorrelationResultWithVariableDto
            //instance = new MessageCorrelationResultWithVariableDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MessageCorrelationResultWithVariableDto
        /// </summary>
        [Test]
        public void MessageCorrelationResultWithVariableDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MessageCorrelationResultWithVariableDto
            //Assert.IsInstanceOfType<MessageCorrelationResultWithVariableDto> (instance, "variable 'instance' is a MessageCorrelationResultWithVariableDto");
        }


        /// <summary>
        /// Test the property 'ResultType'
        /// </summary>
        [Test]
        public void ResultTypeTest()
        {
            // TODO unit test for the property 'ResultType'
        }
        /// <summary>
        /// Test the property 'ProcessInstance'
        /// </summary>
        [Test]
        public void ProcessInstanceTest()
        {
            // TODO unit test for the property 'ProcessInstance'
        }
        /// <summary>
        /// Test the property 'Execution'
        /// </summary>
        [Test]
        public void ExecutionTest()
        {
            // TODO unit test for the property 'Execution'
        }
        /// <summary>
        /// Test the property 'Variables'
        /// </summary>
        [Test]
        public void VariablesTest()
        {
            // TODO unit test for the property 'Variables'
        }

    }

}
