/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * OpenAPI spec version: 7.13.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Camunda.Client.Api;
using Camunda.Client.Model;
using Camunda.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Camunda.Client.Test
{
    /// <summary>
    ///  Class for testing MultiFormDeploymentDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MultiFormDeploymentDtoTests
    {
        // TODO uncomment below to declare an instance variable for MultiFormDeploymentDto
        //private MultiFormDeploymentDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MultiFormDeploymentDto
            //instance = new MultiFormDeploymentDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MultiFormDeploymentDto
        /// </summary>
        [Test]
        public void MultiFormDeploymentDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MultiFormDeploymentDto
            //Assert.IsInstanceOfType<MultiFormDeploymentDto> (instance, "variable 'instance' is a MultiFormDeploymentDto");
        }


        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Test]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }
        /// <summary>
        /// Test the property 'DeploymentSource'
        /// </summary>
        [Test]
        public void DeploymentSourceTest()
        {
            // TODO unit test for the property 'DeploymentSource'
        }
        /// <summary>
        /// Test the property 'DeployChangedOnly'
        /// </summary>
        [Test]
        public void DeployChangedOnlyTest()
        {
            // TODO unit test for the property 'DeployChangedOnly'
        }
        /// <summary>
        /// Test the property 'EnableDuplicateFiltering'
        /// </summary>
        [Test]
        public void EnableDuplicateFilteringTest()
        {
            // TODO unit test for the property 'EnableDuplicateFiltering'
        }
        /// <summary>
        /// Test the property 'DeploymentName'
        /// </summary>
        [Test]
        public void DeploymentNameTest()
        {
            // TODO unit test for the property 'DeploymentName'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

    }

}
