/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * OpenAPI spec version: 7.13.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Camunda.Client.Api;
using Camunda.Client.Model;
using Camunda.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Camunda.Client.Test
{
    /// <summary>
    ///  Class for testing MultiFormVariableBinaryDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MultiFormVariableBinaryDtoTests
    {
        // TODO uncomment below to declare an instance variable for MultiFormVariableBinaryDto
        //private MultiFormVariableBinaryDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MultiFormVariableBinaryDto
            //instance = new MultiFormVariableBinaryDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MultiFormVariableBinaryDto
        /// </summary>
        [Test]
        public void MultiFormVariableBinaryDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MultiFormVariableBinaryDto
            //Assert.IsInstanceOfType<MultiFormVariableBinaryDto> (instance, "variable 'instance' is a MultiFormVariableBinaryDto");
        }


        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'ValueType'
        /// </summary>
        [Test]
        public void ValueTypeTest()
        {
            // TODO unit test for the property 'ValueType'
        }

    }

}
