/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * OpenAPI spec version: 7.13.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Camunda.Client.Api;
using Camunda.Client.Model;
using Camunda.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Camunda.Client.Test
{
    /// <summary>
    ///  Class for testing MultiFormAttachmentDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MultiFormAttachmentDtoTests
    {
        // TODO uncomment below to declare an instance variable for MultiFormAttachmentDto
        //private MultiFormAttachmentDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MultiFormAttachmentDto
            //instance = new MultiFormAttachmentDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MultiFormAttachmentDto
        /// </summary>
        [Test]
        public void MultiFormAttachmentDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MultiFormAttachmentDto
            //Assert.IsInstanceOfType<MultiFormAttachmentDto> (instance, "variable 'instance' is a MultiFormAttachmentDto");
        }


        /// <summary>
        /// Test the property 'AttachmentName'
        /// </summary>
        [Test]
        public void AttachmentNameTest()
        {
            // TODO unit test for the property 'AttachmentName'
        }
        /// <summary>
        /// Test the property 'AttachmentDescription'
        /// </summary>
        [Test]
        public void AttachmentDescriptionTest()
        {
            // TODO unit test for the property 'AttachmentDescription'
        }
        /// <summary>
        /// Test the property 'AttachmentType'
        /// </summary>
        [Test]
        public void AttachmentTypeTest()
        {
            // TODO unit test for the property 'AttachmentType'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Test]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }

    }

}
