/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * OpenAPI spec version: 7.13.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Camunda.Client.Api;
using Camunda.Client.Model;
using Camunda.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Camunda.Client.Test
{
    /// <summary>
    ///  Class for testing ProblemDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProblemDtoTests
    {
        // TODO uncomment below to declare an instance variable for ProblemDto
        //private ProblemDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProblemDto
            //instance = new ProblemDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProblemDto
        /// </summary>
        [Test]
        public void ProblemDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProblemDto
            //Assert.IsInstanceOfType<ProblemDto> (instance, "variable 'instance' is a ProblemDto");
        }


        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Line'
        /// </summary>
        [Test]
        public void LineTest()
        {
            // TODO unit test for the property 'Line'
        }
        /// <summary>
        /// Test the property 'Column'
        /// </summary>
        [Test]
        public void ColumnTest()
        {
            // TODO unit test for the property 'Column'
        }
        /// <summary>
        /// Test the property 'MainElementId'
        /// </summary>
        [Test]
        public void MainElementIdTest()
        {
            // TODO unit test for the property 'MainElementId'
        }
        /// <summary>
        /// Test the property 'ElementIds'
        /// </summary>
        [Test]
        public void ElementIdsTest()
        {
            // TODO unit test for the property 'ElementIds'
        }

    }

}
