/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * OpenAPI spec version: 7.13.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Camunda.Client.Api;
using Camunda.Client.Model;
using Camunda.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Camunda.Client.Test
{
    /// <summary>
    ///  Class for testing ProcessInstanceSuspensionStateDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProcessInstanceSuspensionStateDtoTests
    {
        // TODO uncomment below to declare an instance variable for ProcessInstanceSuspensionStateDto
        //private ProcessInstanceSuspensionStateDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProcessInstanceSuspensionStateDto
            //instance = new ProcessInstanceSuspensionStateDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProcessInstanceSuspensionStateDto
        /// </summary>
        [Test]
        public void ProcessInstanceSuspensionStateDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProcessInstanceSuspensionStateDto
            //Assert.IsInstanceOfType<ProcessInstanceSuspensionStateDto> (instance, "variable 'instance' is a ProcessInstanceSuspensionStateDto");
        }


        /// <summary>
        /// Test the property 'Suspended'
        /// </summary>
        [Test]
        public void SuspendedTest()
        {
            // TODO unit test for the property 'Suspended'
        }
        /// <summary>
        /// Test the property 'ProcessDefinitionId'
        /// </summary>
        [Test]
        public void ProcessDefinitionIdTest()
        {
            // TODO unit test for the property 'ProcessDefinitionId'
        }
        /// <summary>
        /// Test the property 'ProcessDefinitionKey'
        /// </summary>
        [Test]
        public void ProcessDefinitionKeyTest()
        {
            // TODO unit test for the property 'ProcessDefinitionKey'
        }
        /// <summary>
        /// Test the property 'ProcessDefinitionTenantId'
        /// </summary>
        [Test]
        public void ProcessDefinitionTenantIdTest()
        {
            // TODO unit test for the property 'ProcessDefinitionTenantId'
        }
        /// <summary>
        /// Test the property 'ProcessDefinitionWithoutTenantId'
        /// </summary>
        [Test]
        public void ProcessDefinitionWithoutTenantIdTest()
        {
            // TODO unit test for the property 'ProcessDefinitionWithoutTenantId'
        }
        /// <summary>
        /// Test the property 'ProcessInstanceIds'
        /// </summary>
        [Test]
        public void ProcessInstanceIdsTest()
        {
            // TODO unit test for the property 'ProcessInstanceIds'
        }
        /// <summary>
        /// Test the property 'ProcessInstanceQuery'
        /// </summary>
        [Test]
        public void ProcessInstanceQueryTest()
        {
            // TODO unit test for the property 'ProcessInstanceQuery'
        }
        /// <summary>
        /// Test the property 'HistoricProcessInstanceQuery'
        /// </summary>
        [Test]
        public void HistoricProcessInstanceQueryTest()
        {
            // TODO unit test for the property 'HistoricProcessInstanceQuery'
        }

    }

}
