/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * OpenAPI spec version: 7.13.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Camunda.Client.Api;
using Camunda.Client.Model;
using Camunda.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Camunda.Client.Test
{
    /// <summary>
    ///  Class for testing ProcessDefinitionSuspensionStateDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProcessDefinitionSuspensionStateDtoTests
    {
        // TODO uncomment below to declare an instance variable for ProcessDefinitionSuspensionStateDto
        //private ProcessDefinitionSuspensionStateDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProcessDefinitionSuspensionStateDto
            //instance = new ProcessDefinitionSuspensionStateDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProcessDefinitionSuspensionStateDto
        /// </summary>
        [Test]
        public void ProcessDefinitionSuspensionStateDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProcessDefinitionSuspensionStateDto
            //Assert.IsInstanceOfType<ProcessDefinitionSuspensionStateDto> (instance, "variable 'instance' is a ProcessDefinitionSuspensionStateDto");
        }


        /// <summary>
        /// Test the property 'Suspended'
        /// </summary>
        [Test]
        public void SuspendedTest()
        {
            // TODO unit test for the property 'Suspended'
        }
        /// <summary>
        /// Test the property 'ProcessDefinitionId'
        /// </summary>
        [Test]
        public void ProcessDefinitionIdTest()
        {
            // TODO unit test for the property 'ProcessDefinitionId'
        }
        /// <summary>
        /// Test the property 'ProcessDefinitionKey'
        /// </summary>
        [Test]
        public void ProcessDefinitionKeyTest()
        {
            // TODO unit test for the property 'ProcessDefinitionKey'
        }
        /// <summary>
        /// Test the property 'IncludeProcessInstances'
        /// </summary>
        [Test]
        public void IncludeProcessInstancesTest()
        {
            // TODO unit test for the property 'IncludeProcessInstances'
        }
        /// <summary>
        /// Test the property 'ExecutionDate'
        /// </summary>
        [Test]
        public void ExecutionDateTest()
        {
            // TODO unit test for the property 'ExecutionDate'
        }

    }

}
