/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * OpenAPI spec version: 7.13.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Camunda.Client.Api;
using Camunda.Client.Model;
using Camunda.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Camunda.Client.Test
{
    /// <summary>
    ///  Class for testing ProcessDefinitionStatisticsResultDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProcessDefinitionStatisticsResultDtoTests
    {
        // TODO uncomment below to declare an instance variable for ProcessDefinitionStatisticsResultDto
        //private ProcessDefinitionStatisticsResultDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProcessDefinitionStatisticsResultDto
            //instance = new ProcessDefinitionStatisticsResultDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProcessDefinitionStatisticsResultDto
        /// </summary>
        [Test]
        public void ProcessDefinitionStatisticsResultDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProcessDefinitionStatisticsResultDto
            //Assert.IsInstanceOfType<ProcessDefinitionStatisticsResultDto> (instance, "variable 'instance' is a ProcessDefinitionStatisticsResultDto");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Instances'
        /// </summary>
        [Test]
        public void InstancesTest()
        {
            // TODO unit test for the property 'Instances'
        }
        /// <summary>
        /// Test the property 'FailedJobs'
        /// </summary>
        [Test]
        public void FailedJobsTest()
        {
            // TODO unit test for the property 'FailedJobs'
        }
        /// <summary>
        /// Test the property 'Incidents'
        /// </summary>
        [Test]
        public void IncidentsTest()
        {
            // TODO unit test for the property 'Incidents'
        }
        /// <summary>
        /// Test the property 'Definition'
        /// </summary>
        [Test]
        public void DefinitionTest()
        {
            // TODO unit test for the property 'Definition'
        }

    }

}
