/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * OpenAPI spec version: 7.13.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Camunda.Client.Api;
using Camunda.Client.Model;
using Camunda.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Camunda.Client.Test
{
    /// <summary>
    ///  Class for testing ProcessInstanceModificationDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProcessInstanceModificationDtoTests
    {
        // TODO uncomment below to declare an instance variable for ProcessInstanceModificationDto
        //private ProcessInstanceModificationDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProcessInstanceModificationDto
            //instance = new ProcessInstanceModificationDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProcessInstanceModificationDto
        /// </summary>
        [Test]
        public void ProcessInstanceModificationDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProcessInstanceModificationDto
            //Assert.IsInstanceOfType<ProcessInstanceModificationDto> (instance, "variable 'instance' is a ProcessInstanceModificationDto");
        }


        /// <summary>
        /// Test the property 'SkipCustomListeners'
        /// </summary>
        [Test]
        public void SkipCustomListenersTest()
        {
            // TODO unit test for the property 'SkipCustomListeners'
        }
        /// <summary>
        /// Test the property 'SkipIoMappings'
        /// </summary>
        [Test]
        public void SkipIoMappingsTest()
        {
            // TODO unit test for the property 'SkipIoMappings'
        }
        /// <summary>
        /// Test the property 'Instructions'
        /// </summary>
        [Test]
        public void InstructionsTest()
        {
            // TODO unit test for the property 'Instructions'
        }
        /// <summary>
        /// Test the property 'Annotation'
        /// </summary>
        [Test]
        public void AnnotationTest()
        {
            // TODO unit test for the property 'Annotation'
        }

    }

}
