/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * OpenAPI spec version: 7.13.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Camunda.Client.Api;
using Camunda.Client.Model;
using Camunda.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Camunda.Client.Test
{
    /// <summary>
    ///  Class for testing RedeploymentDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RedeploymentDtoTests
    {
        // TODO uncomment below to declare an instance variable for RedeploymentDto
        //private RedeploymentDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RedeploymentDto
            //instance = new RedeploymentDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RedeploymentDto
        /// </summary>
        [Test]
        public void RedeploymentDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RedeploymentDto
            //Assert.IsInstanceOfType<RedeploymentDto> (instance, "variable 'instance' is a RedeploymentDto");
        }


        /// <summary>
        /// Test the property 'ResourceIds'
        /// </summary>
        [Test]
        public void ResourceIdsTest()
        {
            // TODO unit test for the property 'ResourceIds'
        }
        /// <summary>
        /// Test the property 'ResourceNames'
        /// </summary>
        [Test]
        public void ResourceNamesTest()
        {
            // TODO unit test for the property 'ResourceNames'
        }
        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Test]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }

    }

}
