/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * OpenAPI spec version: 7.13.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Camunda.Client.Api;
using Camunda.Client.Model;
using Camunda.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Camunda.Client.Test
{
    /// <summary>
    ///  Class for testing RestartProcessInstanceDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RestartProcessInstanceDtoTests
    {
        // TODO uncomment below to declare an instance variable for RestartProcessInstanceDto
        //private RestartProcessInstanceDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RestartProcessInstanceDto
            //instance = new RestartProcessInstanceDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RestartProcessInstanceDto
        /// </summary>
        [Test]
        public void RestartProcessInstanceDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RestartProcessInstanceDto
            //Assert.IsInstanceOfType<RestartProcessInstanceDto> (instance, "variable 'instance' is a RestartProcessInstanceDto");
        }


        /// <summary>
        /// Test the property 'ProcessInstanceIds'
        /// </summary>
        [Test]
        public void ProcessInstanceIdsTest()
        {
            // TODO unit test for the property 'ProcessInstanceIds'
        }
        /// <summary>
        /// Test the property 'HistoricProcessInstanceQuery'
        /// </summary>
        [Test]
        public void HistoricProcessInstanceQueryTest()
        {
            // TODO unit test for the property 'HistoricProcessInstanceQuery'
        }
        /// <summary>
        /// Test the property 'SkipCustomListeners'
        /// </summary>
        [Test]
        public void SkipCustomListenersTest()
        {
            // TODO unit test for the property 'SkipCustomListeners'
        }
        /// <summary>
        /// Test the property 'SkipIoMappings'
        /// </summary>
        [Test]
        public void SkipIoMappingsTest()
        {
            // TODO unit test for the property 'SkipIoMappings'
        }
        /// <summary>
        /// Test the property 'InitialVariables'
        /// </summary>
        [Test]
        public void InitialVariablesTest()
        {
            // TODO unit test for the property 'InitialVariables'
        }
        /// <summary>
        /// Test the property 'WithoutBusinessKey'
        /// </summary>
        [Test]
        public void WithoutBusinessKeyTest()
        {
            // TODO unit test for the property 'WithoutBusinessKey'
        }
        /// <summary>
        /// Test the property 'Instructions'
        /// </summary>
        [Test]
        public void InstructionsTest()
        {
            // TODO unit test for the property 'Instructions'
        }

    }

}
