/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * OpenAPI spec version: 7.13.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Camunda.Client.Api;
using Camunda.Client.Model;
using Camunda.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Camunda.Client.Test
{
    /// <summary>
    ///  Class for testing RestartProcessInstanceModificationInstructionDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RestartProcessInstanceModificationInstructionDtoTests
    {
        // TODO uncomment below to declare an instance variable for RestartProcessInstanceModificationInstructionDto
        //private RestartProcessInstanceModificationInstructionDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RestartProcessInstanceModificationInstructionDto
            //instance = new RestartProcessInstanceModificationInstructionDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RestartProcessInstanceModificationInstructionDto
        /// </summary>
        [Test]
        public void RestartProcessInstanceModificationInstructionDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RestartProcessInstanceModificationInstructionDto
            //Assert.IsInstanceOfType<RestartProcessInstanceModificationInstructionDto> (instance, "variable 'instance' is a RestartProcessInstanceModificationInstructionDto");
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'ActivityId'
        /// </summary>
        [Test]
        public void ActivityIdTest()
        {
            // TODO unit test for the property 'ActivityId'
        }
        /// <summary>
        /// Test the property 'TransitionId'
        /// </summary>
        [Test]
        public void TransitionIdTest()
        {
            // TODO unit test for the property 'TransitionId'
        }

    }

}
