/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * OpenAPI spec version: 7.13.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Camunda.Client.Api;
using Camunda.Client.Model;
using Camunda.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Camunda.Client.Test
{
    /// <summary>
    ///  Class for testing SchemaLogQueryDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SchemaLogQueryDtoTests
    {
        // TODO uncomment below to declare an instance variable for SchemaLogQueryDto
        //private SchemaLogQueryDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SchemaLogQueryDto
            //instance = new SchemaLogQueryDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SchemaLogQueryDto
        /// </summary>
        [Test]
        public void SchemaLogQueryDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SchemaLogQueryDto
            //Assert.IsInstanceOfType<SchemaLogQueryDto> (instance, "variable 'instance' is a SchemaLogQueryDto");
        }


        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }
        /// <summary>
        /// Test the property 'Sorting'
        /// </summary>
        [Test]
        public void SortingTest()
        {
            // TODO unit test for the property 'Sorting'
        }

    }

}
