/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * OpenAPI spec version: 7.13.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Camunda.Client.Api;
using Camunda.Client.Model;
using Camunda.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Camunda.Client.Test
{
    /// <summary>
    ///  Class for testing SchemaLogQueryDtoSorting
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SchemaLogQueryDtoSortingTests
    {
        // TODO uncomment below to declare an instance variable for SchemaLogQueryDtoSorting
        //private SchemaLogQueryDtoSorting instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SchemaLogQueryDtoSorting
            //instance = new SchemaLogQueryDtoSorting();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SchemaLogQueryDtoSorting
        /// </summary>
        [Test]
        public void SchemaLogQueryDtoSortingInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SchemaLogQueryDtoSorting
            //Assert.IsInstanceOfType<SchemaLogQueryDtoSorting> (instance, "variable 'instance' is a SchemaLogQueryDtoSorting");
        }


        /// <summary>
        /// Test the property 'SortBy'
        /// </summary>
        [Test]
        public void SortByTest()
        {
            // TODO unit test for the property 'SortBy'
        }
        /// <summary>
        /// Test the property 'SortOrder'
        /// </summary>
        [Test]
        public void SortOrderTest()
        {
            // TODO unit test for the property 'SortOrder'
        }

    }

}
