/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * OpenAPI spec version: 7.13.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Camunda.Client.Api;
using Camunda.Client.Model;
using Camunda.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Camunda.Client.Test
{
    /// <summary>
    ///  Class for testing SetJobRetriesByProcessDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SetJobRetriesByProcessDtoTests
    {
        // TODO uncomment below to declare an instance variable for SetJobRetriesByProcessDto
        //private SetJobRetriesByProcessDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SetJobRetriesByProcessDto
            //instance = new SetJobRetriesByProcessDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SetJobRetriesByProcessDto
        /// </summary>
        [Test]
        public void SetJobRetriesByProcessDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SetJobRetriesByProcessDto
            //Assert.IsInstanceOfType<SetJobRetriesByProcessDto> (instance, "variable 'instance' is a SetJobRetriesByProcessDto");
        }


        /// <summary>
        /// Test the property 'ProcessInstances'
        /// </summary>
        [Test]
        public void ProcessInstancesTest()
        {
            // TODO unit test for the property 'ProcessInstances'
        }
        /// <summary>
        /// Test the property 'Retries'
        /// </summary>
        [Test]
        public void RetriesTest()
        {
            // TODO unit test for the property 'Retries'
        }
        /// <summary>
        /// Test the property 'ProcessInstanceQuery'
        /// </summary>
        [Test]
        public void ProcessInstanceQueryTest()
        {
            // TODO unit test for the property 'ProcessInstanceQuery'
        }
        /// <summary>
        /// Test the property 'HistoricProcessInstanceQuery'
        /// </summary>
        [Test]
        public void HistoricProcessInstanceQueryTest()
        {
            // TODO unit test for the property 'HistoricProcessInstanceQuery'
        }

    }

}
