/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * OpenAPI spec version: 7.13.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Camunda.Client.Api;
using Camunda.Client.Model;
using Camunda.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Camunda.Client.Test
{
    /// <summary>
    ///  Class for testing StartProcessInstanceFormDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StartProcessInstanceFormDtoTests
    {
        // TODO uncomment below to declare an instance variable for StartProcessInstanceFormDto
        //private StartProcessInstanceFormDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StartProcessInstanceFormDto
            //instance = new StartProcessInstanceFormDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StartProcessInstanceFormDto
        /// </summary>
        [Test]
        public void StartProcessInstanceFormDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StartProcessInstanceFormDto
            //Assert.IsInstanceOfType<StartProcessInstanceFormDto> (instance, "variable 'instance' is a StartProcessInstanceFormDto");
        }


        /// <summary>
        /// Test the property 'Variables'
        /// </summary>
        [Test]
        public void VariablesTest()
        {
            // TODO unit test for the property 'Variables'
        }
        /// <summary>
        /// Test the property 'BusinessKey'
        /// </summary>
        [Test]
        public void BusinessKeyTest()
        {
            // TODO unit test for the property 'BusinessKey'
        }

    }

}
