/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * OpenAPI spec version: 7.13.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Camunda.Client.Api;
using Camunda.Client.Model;
using Camunda.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Camunda.Client.Test
{
    /// <summary>
    ///  Class for testing StartProcessInstanceDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StartProcessInstanceDtoTests
    {
        // TODO uncomment below to declare an instance variable for StartProcessInstanceDto
        //private StartProcessInstanceDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StartProcessInstanceDto
            //instance = new StartProcessInstanceDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StartProcessInstanceDto
        /// </summary>
        [Test]
        public void StartProcessInstanceDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StartProcessInstanceDto
            //Assert.IsInstanceOfType<StartProcessInstanceDto> (instance, "variable 'instance' is a StartProcessInstanceDto");
        }


        /// <summary>
        /// Test the property 'BusinessKey'
        /// </summary>
        [Test]
        public void BusinessKeyTest()
        {
            // TODO unit test for the property 'BusinessKey'
        }
        /// <summary>
        /// Test the property 'Variables'
        /// </summary>
        [Test]
        public void VariablesTest()
        {
            // TODO unit test for the property 'Variables'
        }
        /// <summary>
        /// Test the property 'CaseInstanceId'
        /// </summary>
        [Test]
        public void CaseInstanceIdTest()
        {
            // TODO unit test for the property 'CaseInstanceId'
        }
        /// <summary>
        /// Test the property 'StartInstructions'
        /// </summary>
        [Test]
        public void StartInstructionsTest()
        {
            // TODO unit test for the property 'StartInstructions'
        }
        /// <summary>
        /// Test the property 'SkipCustomListeners'
        /// </summary>
        [Test]
        public void SkipCustomListenersTest()
        {
            // TODO unit test for the property 'SkipCustomListeners'
        }
        /// <summary>
        /// Test the property 'SkipIoMappings'
        /// </summary>
        [Test]
        public void SkipIoMappingsTest()
        {
            // TODO unit test for the property 'SkipIoMappings'
        }
        /// <summary>
        /// Test the property 'WithVariablesInReturn'
        /// </summary>
        [Test]
        public void WithVariablesInReturnTest()
        {
            // TODO unit test for the property 'WithVariablesInReturn'
        }

    }

}
