/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * OpenAPI spec version: 7.13.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Camunda.Client.Api;
using Camunda.Client.Model;
using Camunda.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Camunda.Client.Test
{
    /// <summary>
    ///  Class for testing TransitionInstanceDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TransitionInstanceDtoTests
    {
        // TODO uncomment below to declare an instance variable for TransitionInstanceDto
        //private TransitionInstanceDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TransitionInstanceDto
            //instance = new TransitionInstanceDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TransitionInstanceDto
        /// </summary>
        [Test]
        public void TransitionInstanceDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TransitionInstanceDto
            //Assert.IsInstanceOfType<TransitionInstanceDto> (instance, "variable 'instance' is a TransitionInstanceDto");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ParentActivityInstanceId'
        /// </summary>
        [Test]
        public void ParentActivityInstanceIdTest()
        {
            // TODO unit test for the property 'ParentActivityInstanceId'
        }
        /// <summary>
        /// Test the property 'ActivityId'
        /// </summary>
        [Test]
        public void ActivityIdTest()
        {
            // TODO unit test for the property 'ActivityId'
        }
        /// <summary>
        /// Test the property 'ActivityName'
        /// </summary>
        [Test]
        public void ActivityNameTest()
        {
            // TODO unit test for the property 'ActivityName'
        }
        /// <summary>
        /// Test the property 'ActivityType'
        /// </summary>
        [Test]
        public void ActivityTypeTest()
        {
            // TODO unit test for the property 'ActivityType'
        }
        /// <summary>
        /// Test the property 'ProcessInstanceId'
        /// </summary>
        [Test]
        public void ProcessInstanceIdTest()
        {
            // TODO unit test for the property 'ProcessInstanceId'
        }
        /// <summary>
        /// Test the property 'ProcessDefinitionId'
        /// </summary>
        [Test]
        public void ProcessDefinitionIdTest()
        {
            // TODO unit test for the property 'ProcessDefinitionId'
        }
        /// <summary>
        /// Test the property 'ExecutionId'
        /// </summary>
        [Test]
        public void ExecutionIdTest()
        {
            // TODO unit test for the property 'ExecutionId'
        }
        /// <summary>
        /// Test the property 'IncidentIds'
        /// </summary>
        [Test]
        public void IncidentIdsTest()
        {
            // TODO unit test for the property 'IncidentIds'
        }
        /// <summary>
        /// Test the property 'Incidents'
        /// </summary>
        [Test]
        public void IncidentsTest()
        {
            // TODO unit test for the property 'Incidents'
        }

    }

}
