/* 
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * OpenAPI spec version: 7.13.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Camunda.Client.Api;
using Camunda.Client.Model;
using Camunda.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Camunda.Client.Test
{
    /// <summary>
    ///  Class for testing TriggerVariableValueDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TriggerVariableValueDtoTests
    {
        // TODO uncomment below to declare an instance variable for TriggerVariableValueDto
        //private TriggerVariableValueDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TriggerVariableValueDto
            //instance = new TriggerVariableValueDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TriggerVariableValueDto
        /// </summary>
        [Test]
        public void TriggerVariableValueDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TriggerVariableValueDto
            //Assert.IsInstanceOfType<TriggerVariableValueDto> (instance, "variable 'instance' is a TriggerVariableValueDto");
        }


        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'ValueInfo'
        /// </summary>
        [Test]
        public void ValueInfoTest()
        {
            // TODO unit test for the property 'ValueInfo'
        }

    }

}
